/*  Flow of Execution of Java Program

   1. Your .java file is compiled by the Java compiler (javac) into bytecode, which is stored in a .class file.
   2. The Java Virtual Machine (JVM) executes the bytecode, translating it into machine code for the host system.
   3. The program runs, and the flow of execution follows the main() method and any called methods.
   4. Control structures (loops, conditionals) dictate the order of execution.
   5. The program terminates when the main() method completes or an unhandled exception occurs.


   JVM Contains an Just-In-Time (JIT) Compiler which works like a interpreter, converting bytecode into native machine code at runtime for improved performance.
   The Bytecode which is generated by the Java compiler is what the JVM executes and it cannot be read by any machine directly let alone executed.
   The JVM also provides features like garbage collection, which helps manage memory automatically.
   
  */